export const GET_MOVIES_BY_NAME = 'GET_MOVIES_BY_NAME';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';
export const GET_MOVIE_COMPLETE = 'GET_MOVIE_COMPLETE';

export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const GET_MOVIE_BY_ID_ERROR = 'GET_MOVIE_BY_ID_ERROR';
export const GET_MOVIE_BY_ID_COMPLETE = 'GET_MOVIE_BY_ID_COMPLETE';


